spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wg_smart?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  elasticsearch:
    ip: localhost:9200