spring:
  datasource:
    url: jdbc:mysql://81.70.7.120:3306/wg_smart?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  elasticsearch:
    rest:
      username: user
      password: 123456
      uris: http://127.0.0.1:9200