spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wg_doc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/